In [2]:
import numpy as np

In [3]:
arry = np.array([1,2,3,4])

In [4]:
arry**4

array([  1,  16,  81, 256])

In [5]:
arry**2

array([ 1,  4,  9, 16])

In [6]:
matrix1 = np.zeros([3,4], dtype = int)

In [7]:
matrix2 = np.ones([3,4], dtype = int)

In [9]:
matrix3 = np.ones([4,2], dtype = int)

In [10]:
matrix1.dot(matrix3)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [11]:
np.random.random([1])

array([0.12061231])

In [12]:
np.random.randint(9)

3