In [1]:
import numpy as np

In [6]:
arry = np.array([1,2,3,4])

In [10]:
arry**4

array([  1,  16,  81, 256])

In [12]:
arry**2

array([ 1,  4,  9, 16])

In [20]:
matrix1 = np.zeros([3,4], dtype = int)

In [21]:
matrix2 = np.ones([3,4], dtype = int)

In [24]:
matrix1.dot(matrix2)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [25]:
matrix3 = np.ones([4,2], dtype = int)

In [27]:
matrix1.dot(matrix3)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [34]:
np.random.random([1])

array([0.90687824])

In [36]:
np.random.randint(9)

3

In [ ]:
numpu